apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio
      initContainers:
        - name: create-bucket
          image: docker-hub.repo1.uhc.com/busybox
          volumeMounts:
            - name: data
              mountPath: "/data"
          command:
            - /bin/sh
            - -c
            - mkdir -p /data/kubeadm-backup-dev
      containers:
        - name: minio
          volumeMounts:
            - name: data
              mountPath: "/data"
          image: docker-hub.repo1.uhc.com/minio/minio:RELEASE.2020-04-10T03-34-42Z
          args:
            - server
            - /data
          env:
            - name: MINIO_ACCESS_KEY
              value: "minio"
            - name: MINIO_SECRET_KEY
              value: "minio123"
          ports:
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 120
            periodSeconds: 20
