version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run:
          name: Create workspace
          command: mkdir -p images
      - run:
          name: Build binary
          command: make build
      - setup_remote_docker
      - run:
          name: Build Docker Images
          command: |
            DOCKER_TAG="master"
            if [ -n "$CIRCLE_TAG" ]; then
              DOCKER_TAG=$CIRCLE_TAG
            fi
            make docker DOCKER_REPO=docker.io/rmb938 DOCKER_IMAGE_NAME=kubeadm-backup DOCKER_IMAGE_TAG=${DOCKER_TAG}
      - run:
          name: Save Docker Images
          command: |
            DOCKER_TAG="master"
            if [ -n "$CIRCLE_TAG" ]; then
              DOCKER_TAG=$CIRCLE_TAG
            fi
            docker save -o images/amd64.tar docker.io/rmb938/kubeadm-backup:${DOCKER_TAG}-amd64
            docker save -o images/armv7.tar docker.io/rmb938/kubeadm-backup:${DOCKER_TAG}-armv7
      - persist_to_workspace:
          root: .
          paths: images

  publish-image:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: /workspace
      - run:
          name: Load Docker Images
          command: |
            docker load -i /workspace/images/amd64.tar
            docker load -i /workspace/images/armv7.ta
      - run:
          name: Push Docker Images
          command: |
            DOCKER_TAG="master"
            if [ -n "$CIRCLE_TAG" ]; then
              DOCKER_TAG=$CIRCLE_TAG
            fi
            echo $DOCKER_PASSWORD | docker login docker.pkg.github.com -u rmb938 --password-stdin
            make docker-push DOCKER_REPO=docker.io/rmb938 DOCKER_IMAGE_NAME=kubeadm-backup DOCKER_IMAGE_TAG=${DOCKER_TAG}
            make docker-manifest DOCKER_REPO=docker.io/rmb938 DOCKER_IMAGE_NAME=kubeadm-backup DOCKER_IMAGE_TAG=${DOCKER_TAG}

workflows:
  version: 2
  kubeadm-backup:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish-image:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
