apiVersion: v1
kind: Secret
metadata:
  name: kubeadm-backup-blob-config
stringData:
  config.yaml: |-
    type: S3
    config:
        endpoint: "minio:9000"
        insecure: true
        bucket: "kubeadm-backup-dev"
        access_key: "minio"
        secret_key: "minio123"
